services:
  wordpress:
    depends_on:
      - mariadb
      - redis
    environment:
      - ENABLE_REDIS_CACHE=true

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    env_file: .env
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: always

  ftp_server:
    build: ./requirements/bonus/ftp_server
    container_name: ftp_server
    env_file: .env
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    ports:
      - "21:21"
      - "40000-40110:40000-40110"
    networks:
      - app-network
    restart: always

  static:
    build: ./requirements/bonus/static_page
    container_name: static-website
    networks:
      - app-network
    restart: always
