[PHP]
; default in alpine is 2M, not setting this may cause PHP-FPM refuse
; to upload files larger than 2Mb
upload_max_filesize = 64M

; same case, tiny max in alpine 8mb
post_max_size = 64M

;max ram the php-fpm use, deafult 128M, may cause memory size exhausted errors
memory_limit = 256M

; max time a script can run before being killed
max_execution_time = 300
