local_enable=YES

write_enable=YES

chroot_local_user=YES
allow_writeable_chroot=YES
seccomp_sandbox=NO

pasv_enable=YES
pasv_promiscuous=YES
port_enable=YES
pasv_min_port=40000
pasv_max_port=40110
pasv_address=127.0.0.1

listen=YES
listen_ipv6=NO
background=NO
